import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import { ToastContainer } from "react-toastify";

import ClientProvider from "@/components/Hoc/ClientProvider";
import Navbar from "@/components/Home/Nav/Nav";
import Footer from "@/components/Home/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bhupalan-k",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navbar />
          <Suspense
            fallback={<div className='loading'>
              <p>Loading Job Details, Please try again Later</p>
            </div>}>
            {children}
            <ToastContainer autoClose={1500} />
          </Suspense>
          <Footer />
        </body>
      </html>
    </ClientProvider>
  );
}
