export const experience = [
    { value: '', label: 'Experience', disabled: true, hidden: true },
    { value: '0year', label: '0 Year' },
    { value: '1year', label: '1 Year' },
    { value: '2years', label: '2 Years' },
    { value: '3years', label: '3 Years' },
    { value: '4years', label: '4 Years' },
    { value: '5years', label: '5 Years' },
    { value: '6years', label: '6 Years' },
    { value: '7years', label: '7 Years' },
    { value: '8years', label: '8 Years' },
    { value: '9years', label: '9 Years' },
    { value: '10years', label: '10 Years' },
    { value: '11years', label: '11 Years' },
    { value: '12years', label: '12 Years' },
    { value: '13years', label: '13 Years' },
    { value: '14years', label: '14 Years' },
    { value: '15years', label: '15 Years' },
    { value: '16years', label: '16 Years' },
    { value: '17years', label: '17 Years' },
    { value: '18years', label: '18 Years' },
    { value: '19years', label: '19 Years' },
    { value: '20years', label: '20 Years' },
    { value: '21years', label: '21 Years' },
    { value: '22years', label: '22 Years' },
    { value: '23years', label: '23 Years' },
    { value: '24years', label: '24 Years' },
    { value: '25years', label: '25 Years' },
    { value: '26years', label: '26 Years' },
    { value: '27years', label: '27 Years' },
    { value: '28years', label: '28 Years' },
    { value: '29years', label: '29 Years' },
    { value: '30years', label: '30 Years' },
  ];

  export const skillOptions = [
    { value: 'html', label: 'HTML' },
    { value: 'css', label: 'CSS' },
    { value: 'javascript', label: 'JavaScript' },
    { value: 'typescript', label: 'TypeScript' },
    { value: 'react', label: 'React' },
    { value: 'nextjs', label: 'Next.js' },
    { value: 'vuejs', label: 'Vue.js' },
    { value: 'angular', label: 'Angular' },
    { value: 'redux', label: 'Redux' },
    { value: 'mui', label: 'Material-UI' },
    { value: 'bootstrap', label: 'Bootstrap' },
    { value: 'tailwindcss', label: 'Tailwind CSS' },
    { value: 'sass', label: 'SASS' },
    { value: 'git', label: 'Git' },
    { value: 'api', label: 'API Integration' },
    { value: 'webpack', label: 'Webpack' },
    { value: 'babel', label: 'Babel' },
    { value: 'jest', label: 'Jest' },
    { value: 'cypress', label: 'Cypress' },
    { value: 'storybook', label: 'Storybook' },
    { value: 'nodejs', label: 'Node.js' },
    { value: 'express', label: 'Express.js' },
    { value: 'mongodb', label: 'MongoDB' },
    { value: 'firebase', label: 'Firebase' },
    { value: 'graphql', label: 'GraphQL' },
    { value: 'docker', label: 'Docker' },
    { value: 'figma', label: 'Figma' },
    { value: 'photoshop', label: 'Photoshop' },
    { value: 'seo', label: 'SEO Optimization' },
    { value: 'accessibility', label: 'Web Accessibility' },
  ];
    